### ISSUE TITLE
How is this generated? macs2_peaks_final.replicated.narrowPeak

### ISSUE THREAD

**Issue by YichaoOU** [ijuric/MAPS#12]
For the narrowPeak file, is it just using common MACS2 parameters for TF or histones?

I mean, do I first need to treat the HiChIP data as a paired-end chip-seq data and do peak calling? and then use the narrowpeak file for this hichip pipeline?

Thanks,
Yichao

**Comment by ijuric** [comment]
So, you need to have .narrowpeak file to run MAPS. How you obtain it is a
different issue which will depend on many things. We usually run MACS2 on
chipseq data to call peaks, but sometimes you might be lucky and work with
cell types that someone else used before and there is a good list of 1D
peaks in the literature.
I hope this helps.
Ivan
