### ISSUE TITLE
MAPS modeling step fails

### ISSUE THREAD

**Issue by danledinh** [ijuric/MAPS#29]
Do you know what is causing this error during the MAPS module?

```
Error in if (one.more) { : missing value where TRUE/FALSE needed
Calls: pospoisson_regression -> vglm -> vglm.fitter
Execution halted
```

I do not have the error when running the Arima test data. It only fails on my data.

**Comment by armenabnousi** [comment]
I have seen this error when using VGAM package (vglm) under R-v4, reverting to R version 3.5, fixed it for me. I'm not exactly sure what causes this problem yet.

**Comment by danledinh** [comment]
I reverted back to R version 3.5.0 and I am still getting the same error. Any other ideas?

**Comment by Zojka** [comment]
Hi, I'm getting the same error:

```bash
[1] "loading chromosome chrX .xor"
[1] "run 1 : regression on chromosome chr1"
[1] "/mnt/raid/zparteka/hichip/gm19240/ctcf_pulled/out_maps//MAPS_output/GM19240_CTCF_pulled_20201112_140225/reg_raw.chr1.GM19240_CTCF_pulled.10k.and.MAPS2_pospoisson"
Error in if (one.more) { : missing value where TRUE/FALSE needed
Calls: pospoisson_regression -> vglm -> vglm.fitter
Execution halted
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
```
I already analyzed multiple different samples using your software (and the same setup) and didn't get this kind of error before.

**Comment by armenabnousi** [comment]
what is the depth of your dataset? Would it possible for you to share your data for us to check? It seems chromosome 1 is failing, if you can share the bedpe files for chr1 we can try running  it on our side.

**Comment by danledinh** [comment]
Can you provide a docker container or dockerfile to create the MAPS environment that you use?

**Comment by Zojka** [comment]
Hi, I'm working on two biological replicates pulled together to one file (311,615,930 reads in total). I previously ran the software on replicates before pulling and everything worked just fine with the same setup. The dataset is not published yet, but I can try to send you the .bedpe file via Google Drive (it's around 544 Mb).

Regarding my setup: I'm not working with Docker, but I double checked the R version and indeed the version is 3.6.3
Is it possible that it's working fine with some samples and is failing with others?

**Comment by Zojka** [comment]
I downgraded R to 3.4.3 and it didn't help. Do you have any other ideas?

**Comment by armenabnousi** [comment]
We have noticed the problem occurs using VGAM_1.1-4. Try using VGAM_1.1-3.

**Comment by Zojka** [comment]
That's what I did. I downgraded this package to an even older version two weeks ago and it works. Thanks.

**Comment by danledinh** [comment]
Worked for me too! Thanks.

**Comment by nlthanhthanh** [comment]
I also encountered the exact same problem. Reverted the VGAM to 1.1-3 and it worked for me! Thanks a lot.

**Comment by julienrichardalbert** [comment]
Same problem, where only one of my datasets failed. Reverting VGAM to 1.1-3 did not help.

**Comment by AshleyNDoerfler** [comment]
I tried downgrading R to 3.4.3 and installing VGAM 1.1.3, but it said that that version of VGAM wasn't available. The project that I am trying to replicate is R 3.6.0, and same thing. Would using docker help resolve my issue?
