### ISSUE TITLE
AND/XOR interactions from final output

### ISSUE THREAD

**Issue by Zojka** [ijuric/MAPS#35]
Hi,
Is there a way to identify AND vs XOR significant interations from the final *.sig3Dinteractions.bedpe file? Or is there any way to get two separate sets for those interactions?
Thanks!

**Comment by armenabnousi** [comment]
You can merge those files with the *.MAPS2_pospoisson.xor and *.MAPS2_pospoisson.and files to separate them into XOR and AND sets.

**Comment by Zojka** [comment]
Thanks!
